In [8]:
import pandas as pd
import numpy as np
import os
import warnings

warnings.filterwarnings("ignore")
os.listdir('../data')

['data_processed.csv', 'UPPLY-SEAPORTS.csv']

In [9]:
df = pd.read_csv('../data/UPPLY-SEAPORTS.csv', sep=';', index_col = 'name')
data_copia = df.copy()
df.sample(5)

            code  latitude  longitude country_code zone_code
name
Dutzow     USZDZ   38.6000   -90.9833           US   NAE-USA
Rozi       INROZ   22.5667    70.0333           IN    ME-IPB
Fawnskin   USF2S   34.2667  -116.9333           US   NAW-USA
Ewijk      NLEWK   51.8670     5.7330           NL    EU-NEU
Nashville  USVQV   42.6000   -85.0830           US   NAE-CAN

In [10]:
df.isna().sum()

code            0
latitude        0
longitude       0
country_code    1
zone_code       0
dtype: int64

In [11]:
df.dropna(subset=["country_code"], inplace=True)
df.drop_duplicates()

                        code   latitude   longitude country_code zone_code
name
Abu Dhabi              AEAUH  24.466700   54.366700           AE    ME-MID
Abu Musa               AEAMU  25.866700   55.016700           AE    ME-MID
Ahmed Bin Rashid Port  AEARP  25.533300   55.550000           AE    ME-MID
Al Fujayrah            AEFJR  25.116700   56.333300           AE    ME-MID
Al Jazeera Port        AEJAZ  25.716700   55.800000           AE    ME-MID
...                      ...        ...         ...          ...       ...
Saipan                 MPSPN  15.185048  145.746726           MP    OC-OCE
Norfolk Island         NFNLK -29.040835  167.954712           NF    OC-OCE
Koror                  PWROR   7.337565  134.488947           PW    OC-OCE
Funafuti               TVFUN  -8.521147  179.196193           TV    OC-OCE
Apia                   WSAPW -13.850696 -171.751355           WS    OC-OCE

[14268 rows x 5 columns]

In [12]:
# Se crean nuevas columnas: Hemisferio Norte, Sur, Este, Oeste

df['hemisphere_NS'] = np.where(
    df['latitude'] >= 0,
    'North',
    'South'
)

df['hemisphere_WE'] = np.where(
    df['longitude'] >= 0,
    'East',
    'West'
    
)

In [13]:
df.reset_index(drop=True, inplace=True)
df.drop(columns= ['code', 'country_code'], inplace=True)
df.set_index('latitude', inplace= True)

In [14]:
df.to_csv('../data/data_processed.csv')